/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        card: 'var(--color-card)',
        cardForeground: 'var(--color-card-foreground)',
        popover: 'var(--color-popover)',
        popoverForeground: 'var(--color-popover-foreground)',
        primary: 'var(--color-primary)',
        primaryForeground: 'var(--color-primary-foreground)',
        secondary: 'var(--color-secondary)',
        secondaryForeground: 'var(--color-secondary-foreground)',
        muted: 'var(--color-muted)',
        mutedForeground: 'var(--color-muted-foreground)',
        accent: 'var(--color-accent)',
        accentForeground: 'var(--color-accent-foreground)',
        destructive: 'var(--color-destructive)',
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        ring: 'var(--color-ring)',
        chart1: 'var(--color-chart-1)',
        chart2: 'var(--color-chart-2)',
        chart3: 'var(--color-chart-3)',
        chart4: 'var(--color-chart-4)',
        chart5: 'var(--color-chart-5)',
        sidebar: 'var(--color-sidebar)',
        sidebarForeground: 'var(--color-sidebar-foreground)',
        sidebarPrimary: 'var(--color-sidebar-primary)',
        sidebarPrimaryForeground: 'var(--color-sidebar-primary-foreground)',
        sidebarAccent: 'var(--color-sidebar-accent)',
        sidebarAccentForeground: 'var(--color-sidebar-accent-foreground)',
        sidebarBorder: 'var(--color-sidebar-border)',
        sidebarRing: 'var(--color-sidebar-ring)',
      },
    },
  },
  plugins: [],
}
